In [1]:
import torch

# 建立都是0或都是1的张量

In [3]:
a1=torch.ones(3,3,3)

In [4]:
a1

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [5]:
a2=torch.zeros(3,3,3)

In [6]:
a2

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

# 建立具体数字的张量

In [8]:
b=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
b

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# 建立随机数张量

In [11]:
c1=torch.randn(3,3,3)  #生成标准正态中的随机数

In [12]:
c1

tensor([[[ 0.2772, -0.2654, -0.7203],
         [-0.8913,  0.2562,  0.3291],
         [-1.8960,  0.8657,  1.5168]],

        [[-0.3907,  0.8525, -0.1171],
         [-0.6982, -0.3195,  0.5392],
         [-0.6002,  0.7961, -0.4157]],

        [[-0.0658,  0.6032, -0.1488],
         [-0.4625,  2.2980,  0.1593],
         [ 0.6360, -0.0047, -1.6114]]])

In [35]:
c2=torch.rand(3,3,3)  #生成均匀分布的随机数[0,1)

In [37]:
c2

tensor([[[0.3082, 0.7546, 0.6200],
         [0.2912, 0.5472, 0.7322],
         [0.6657, 0.6016, 0.9108]],

        [[0.3083, 0.3002, 0.7360],
         [0.8480, 0.4950, 0.4552],
         [0.9070, 0.9731, 0.4242]],

        [[0.8435, 0.1315, 0.0992],
         [0.1720, 0.9934, 0.1571],
         [0.7504, 0.9448, 0.6693]]])

# 张量索引

In [14]:
b[1:,0]

tensor([4, 7])

## 同一中括号内索引完还在统一中括号内

In [16]:
b[1:,1:]

tensor([[5, 6],
        [8, 9]])